// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRMBeL6Xdj4m9bwmsLSKbcG7sKACCKJAw',
    appId: '1:312064957830:web:dbf2b7c89a3d9ead5ea007',
    messagingSenderId: '312064957830',
    projectId: 'conch-e6c0a',
    authDomain: 'conch-e6c0a.firebaseapp.com',
    storageBucket: 'conch-e6c0a.appspot.com',
    measurementId: 'G-D7FW7MYTMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK6iRbsrdW9OmWFWHIYSSJ4D5jdkqSWzU',
    appId: '1:312064957830:android:b25ecce80e50db2a5ea007',
    messagingSenderId: '312064957830',
    projectId: 'conch-e6c0a',
    storageBucket: 'conch-e6c0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeWN6B5Gbp2mjhJHKqi8khgohT_9JkD_I',
    appId: '1:312064957830:ios:dcaeeac34a9a96f35ea007',
    messagingSenderId: '312064957830',
    projectId: 'conch-e6c0a',
    storageBucket: 'conch-e6c0a.appspot.com',
    iosClientId: '312064957830-2eraititb0rckooq71s7op0a0k4e8948.apps.googleusercontent.com',
    iosBundleId: 'com.aniketwarty.conch.conch',
  );
}
